### ISSUE TITLE
Idea: Define logic too

### ISSUE THREAD

**Issue by diondokter** [diondokter/device-driver#70]
Currently the input is very declarative: This register exists and that buffer exists, etc...
There's no logic anywhere.

This doesn't have to be the case. Lots of device have really simple interfaces.
What if you could put how to read/write in the manifest too?

Something like:
```yaml
interfaces:
  spi:
    write_register:
    - Write: 0x00
    - Write: address
    - Write: data
    read_register:
    - Write: 0x01
    - Write: address
    - Read: data
```
This would work for the S2lp radio.

Not everything can be captured like this, but if 90% can, that'd be very valuable.

Additionally in the same vain, some routines could be added too:
```yaml
routines:
  - init:
    - write_register:
        name: foo
        value:
          - bar: 12
          - xen: false
```

This would probably need some control flow too which would be some amount of cursed, but probably fine.
